### ISSUE TITLE
Supporting async / await

### ISSUE THREAD

**Issue by reggi** [apex/node-apex#1]
I'd love if there was a way to use this module with async / await.

``` js
export default λ(event => {
  let doSomeStuff = await stuffToDo("0")
  let otherStuff = await stuffToDo("1")
  return {
    doSomeStuff,
    otherStuff
  }
})
```

I've tried a couple of different things, most of which are noobish but kinda intuitive.
- `export async default λ(event => {`
- `export default async  λ(event => {`
- `export default λ(event => async () {`

I think this just needs some kind alternative handler. Just not sure of a design.

**Comment by ajcrites** [comment]
@reggi this library in and of itself doesn't need to do anything to support async/await, but the code that uses it either has to use a preprocessor or run in an environment that does support them. 

I think what you're after is:

```
export default λ(async event => {
```

**Comment by tj** [comment]
yep, as long as you pass a promise to λ you're good
