### ISSUE TITLE
Support node 4.3 lambda recommendations for callbacks

### ISSUE THREAD

**Issue by ajcrites** [apex/node-apex#2]
[From the AWS docs](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-using-old-runtime.html#transition-to-new-nodejs-runtime) using the `callback` argument to the lambda function handler is preferred over `context[method]`.

I've already created a version that supports this and published it: https://github.com/ajcrites/node43-apex

I think that it makes sense to have these as separate repos/packages, but it still seems like this package is used quite a bit.

**Comment by tj** [comment]
SGTM, as long as we major-bump it'd be fine!

**Comment by tj** [comment]
forgot to close
